---
    - name: Create apache2 web index.html
      template:
        src: /home/tranx/ansible2/templates/index.html.j2
        dest: /var/www/html/index.html

    - name: Apache service is started and enable
      service:
        name: apache2
        state: restarted
        enabled: true
