#prometheus
---
#    - name: Update apt cache
#      apt:
#        update_cache: yes

    - name: Install necessary packages and Prometheus monitoring logging serv
      shell: "sudo apt install -y prometheus prometheus-node-exporter"
#      shell: "sudo apt install -y jnettop htop iotop iftop atop iptraf-ng nmon && sudo apt install -y prometheus prometheus-node-exporter"

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start prometheus-node-exporter service
      systemd:
        name: prometheus-node-exporter
        state: started
        enabled: yes

    - name: Remove existing prometheus.yml file (if exists)
      file:
        path: /etc/prometheus/prometheus.yml
        state: absent
      tags: prometheus

    - name: Copy Prometheus configuration from GitHub (For monitoring)
      copy:
        src: /home/tranx/TranxOtus/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
      tags: prometheus

    - name: Restart prometheus and etc
      shell: "sudo systemctl daemon-reload && sudo systemctl start prometheus-node-exporter && sudo systemctl enable prometheus-node-exporter"
